import React, { useEffect } from "react";
import { InertiaLink, useForm } from "@inertiajs/inertia-react";

import Admin from "../../../Layouts/Admin";
import NaviBar from "../../../Components/NaviBar";

import AmaranthIcon, {
  aiCheck,
  aiSpinnerThird,
  aiArrowUp,
  aiClockRotateLeft,
  aiFlag,
} from "@changewindows/amaranth";

import clsx from "clsx";
import Suggestion from "./_Suggestion";

export default function Index({
  can,
  status = null,
  errors,
  suggestion,
}) {
  const { data, setData, post, processing } = useForm({
    build: "",
    file: "",
  });

  function submit(e) {
    e.preventDefault();
    post(route("admin.flags.batch"));
  }

  useEffect(() => {
    if (data.file) {
      setData(
        "build",
        data.file[0]?.name.substr(0, data.file[0].name.lastIndexOf("."))
      );
    }
  }, [data.file]);

  return (
    <Admin>
      <NaviBar>
        <nav className="navbar navbar-expand navbar-light sticky-top">
          <div className="container">
            <ul className="navbar-nav me-auto">
              <li className="nav-item">
                <InertiaLink className="nav-link active" href="/admin/flags">
                  <AmaranthIcon icon={aiFlag} />{" "}
                  <span className="d-none d-sm-inline-block ms-1">Manage</span>
                </InertiaLink>
              </li>
              <li className="nav-item">
                <InertiaLink className="nav-link" href="/admin/flags/history">
                  <AmaranthIcon icon={aiClockRotateLeft} />{" "}
                  <span className="d-none d-sm-inline-block ms-1">History</span>
                </InertiaLink>
              </li>
            </ul>
          </div>
        </nav>
      </NaviBar>

      <div className="container my-2">
        {status && (
          <div className="alert alert-success">
            <AmaranthIcon icon={aiCheck} /> {status}
          </div>
        )}
        <div className="row g-1">
          {can.createFlags && (
            <>
              <div className="col-12 col-md-4 my-4 my-md-0">
                <h4 className="h5 mb-0">Upload flags</h4>
                <p className="text-muted mb-0">
                  <small>Enter a file generated by Mach2.</small>
                </p>
              </div>
              <form onSubmit={submit} className="col-12 col-md-8">
                <div className="card">
                  <div className="card-body">
                    <div className="row g-3">
                      <div className="col-12 col-sm-6">
                        <div className="form-floating">
                          <input
                            type="file"
                            className={clsx("form-control flex-grow-1", {
                              "is-invalid": errors.file,
                            })}
                            id="file"
                            name="file"
                            onChange={(e) => setData("file", e.target.files)}
                          />
                        </div>
                      </div>
                      <div className="col-12 col-sm-6">
                        <div className="form-floating">
                          <input
                            type="text"
                            className="form-control"
                            id="build"
                            value={data.build}
                            onChange={(e) => setData("build", e.target.value)}
                          />
                          <label htmlFor="build">Build</label>
                        </div>
                      </div>
                      <div className="col-12 d-flex justify-content-end">
                        <button
                          type="submit"
                          className="btn btn-primary btn-sm"
                          disabled={processing}
                        >
                          <AmaranthIcon
                            icon={processing ? aiSpinnerThird : aiArrowUp}
                            spin={processing}
                          />{" "}
                          {processing ? "Processing..." : "Upload"}
                        </button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </>
          )}
          <h4>Moderate suggestions</h4>
          {suggestion ? <Suggestion suggestion={suggestion} /> : <i>No suggestions...</i>}
        </div>
      </div>
    </Admin>
  );
}
